[package]
name = "hypaper-renderer"
description = "GPU rendering backend via wgpu"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
hypaper-types = { path = "../hypaper-types" }
hypaper-scene = { path = "../hypaper-scene" }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
